import inspect
import textwrap
import enum
from PySide6.QtCore import Signal, Slot
from .const import PY_TO_QML_TYPE


class QmlTypesGenerator:
    """Генератор .qmltypes файла"""

    def __init__(self, cls, qml_import_name, path, source_path):
        self.cls = cls
        self.path = path
        self.source_path = source_path
        self.qml_import_name = qml_import_name

    def generate(self):
        header = textwrap.dedent("""\
            import QtQuick.tooling 1.2

            // This file describes the plugin-supplied types contained in the library.
            // It is used for QML tooling purposes only.
            //
            // Auto-generated by QmlModuleInterface
        """)
        component_1 = self._format_component_1()

        body = textwrap.indent(component_1, "    ")
        template = f"{header}\nModule {{\n{body}\n}}\n"

        # 🔥 Проверяем — файл существует и содержимое совпадает
        if self.path.exists():
            existing = self.path.read_text(encoding="utf-8")
            if existing.strip() == template.strip():
                return

        # 🔥 Записываем только если файл новый или изменился
        self.path.write_text(template, encoding="utf-8")
        print(f"[QmlModuleInterface] Сгенерирован {self.path.name}")


    # -------------------------------------------------------------------

    def _format_component_1(self):
        base = self._detect_qt_base()
        src = self.source_path.as_posix()

        enums = self._extract_enums()
        signals = self._extract_signals()
        properties = self._extract_properties()
        methods = self._extract_methods()

        parts = enums + signals + properties + methods

        body = "\n".join(line for line in parts)

        component_form_1 = f"""\
                                Component {{
                                    file: "{src}"
                                    lineNumber: 0
                                    name: "{self.cls.__name__}"
                                    accessSemantics: "reference"
                                    prototype: "{base}"
                                    exports: ["{self.qml_import_name}/{self.cls.__name__} 1.0"]
                                    isCreatable: false
                                    isSingleton: false
                                    exportMetaObjectRevisions: [256]
                                    {body}
                                }}
                            """

        data = textwrap.dedent(component_form_1)

        return data

    # -------------------------------------------------------------------

    def _extract_enums(self):
        result = []
        for name, obj in self.cls.__dict__.items():            
            if isinstance(obj, enum.EnumMeta):
                values = ", ".join(f'"{e.name}"' for e in obj)
                result.append(f'Enum {{ name: "{name}"; values: [{values}] }}')
        return result

    def _extract_signals(self):
        result = []
        for name, obj in self.cls.__dict__.items():
            if isinstance(obj, Signal):
                sig_types = getattr(obj, "_types", [])
                params = []
                for i, t in enumerate(sig_types):
                    tname = getattr(t, "__name__", str(t))
                    params.append(f'Parameter {{ name: "arg{i+1}"; type: "{tname}" }}')
                params_str = "\n            ".join(params)
                result.append(f'Signal {{ name: "{name}"{"\n            " + params_str if params else ""} }}')
        return result

    def _extract_properties(self):
        """Извлекает Property из staticMetaObject с QML-конверсией типов"""
        result = []

        meta = getattr(self.cls, "staticMetaObject", None)
        if not meta:
            return result

        base_meta = meta.superClass()
        base_prop_count = base_meta.propertyCount() if base_meta else 0

        count = meta.propertyCount()
        for i in range(base_prop_count, count):
            mprop = meta.property(i)
            name = mprop.name()

            # 🔹 Тип
            type_name = mprop.typeName() or "var"
            type_name = PY_TO_QML_TYPE.get(type_name, type_name)

            # 🔹 Notify
            if mprop.hasNotifySignal():
                notify_obj = mprop.notifySignal().name()
                if hasattr(notify_obj, "data"):
                    notify = notify_obj.data().decode()
                elif isinstance(notify_obj, (bytes, bytearray)):
                    notify = notify_obj.decode()
                else:
                    notify = str(notify_obj)
                notify = f'"{notify}"'
            else:
                notify = "undefined"

            # 🔹 Writable
            writable = "true" if mprop.isWritable() else "false"

            result.append(
                f'Property {{ name: "{name}"; type: "{type_name}"; '
                f'isWritable: {writable}; notify: {notify} }}'
            )

        return result

    def _extract_methods(self):
        result = []
        for name, method in inspect.getmembers(self.cls, inspect.isfunction):
            if name.startswith("_"):
                continue
            sig = inspect.signature(method)
            params = []
            for pname, p in sig.parameters.items():
                if pname == "self":
                    continue
                t = getattr(p.annotation, "__name__", "var") if p.annotation != inspect._empty else "var"
                params.append(f'Parameter {{ name: "{pname}"; type: "{t}" }}')

            param_str = "\n            ".join(params)
            rettype = getattr(method.__annotations__.get("return"), "__name__", "void")
            result.append(f'Method {{ name: "{name}"; type: "{rettype}"{"\n            " + param_str if params else ""} }}')
        return result

    def _detect_qt_base(self):
        for base in self.cls.__mro__[1:]:
            if base.__module__.startswith("PySide6."):
                return base.__name__
        return "QObject"
